spring.application.name=fixcampus
spring.datasource.url=${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:fixcampus}}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Clave local de prueba de 64 caracteres ASCII. En Render se usa JWT_SECRET.
jwt.secret=${JWT_SECRET:fc63a8b99dead0894abb684fe27e3683022574f1295a69344e5553e913f523f7}
server.port=${PORT:8080}
